### ISSUE TITLE
TypeError: rds.startDBInstance is not a function

### ISSUE THREAD

**Issue by ayajshaikh** [perevernihata/rds-lambda-stop-start#1]
I am getting following error:

> TypeError: rds.startDBInstance is not a function
    at module.exports (/var/task/start.js:8:7)
    at event.instances.forEach (/var/task/index.js:13:17)
    at Array.forEach (native)
    at exports.handler  (/var/task/index.js:5:21) 

What could be the problem?

**Comment by perevernihata** [comment]
@ayajshaikh are you getting this error locally or on AWS lambda? you will get this error if you just copy function to the aws lambda, since for some reason they do not provide latest aws sdk.
If this is a local error - gimme your node and npm version please

**Comment by ayajshaikh** [comment]
@perevernihata I am getting this error on AWS lambda. How do I make sure that I get the latest AWS SDK on Lambda! Is there any way where I can check the current version on Lambda?

**Comment by perevernihata** [comment]
@ayajshaikh, make sure you run 'npm install' and then add your node_modules folder to the zip archive before uploading it to lambda.

**Comment by perevernihata** [comment]
@ayajshaikh did it solve the issue? if yes - I'm closing the issue

**Comment by ayajshaikh** [comment]
yes. npm install did the trick thanks.
